change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  ## Changes
  $CHANGES

autolabeler:
  - label: enhancement
    branch:
      - '/^feat(ure)?[/-].+/'
  - label: bug
    branch:
      - '/^fix[/-].+/'
  - label: emergency
    branch:
      - '/^hotfix[/-].+/'
  - label: test
    branch:
      - '/^test[/-].+/'
  - label: refactor
    branch:
      - '/^refactor[/-].+/'
  - label: documentation
    branch:
      - '/^doc[/-].+/'