name: Create Release Note

on:
  # PR が閉じられた時に自動実行する
  pull_request:
    branches:
      - main
    types:
      - closed

#permissions:
 # contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    ## ここだけdeploy-to-production.ymlに入れればよさそう
    steps:
      - name: Create Release Note
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ env.version }}
        with:
          # 自動でpublishまでする場合コメントアウトを外す
          # publish: true
          name: Release ${{ env.version }}
          tag: ${{ env.version }}
          version: ${{ env.version }}