name: Create Release Note

on:
  # PR が閉じられた時に自動実行する
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    ## ここだけdeploy-to-production.ymlに入れればよさそう
    steps:
      - name: Create Release Note
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #TODO v202402261910は ${{ env.version }}に戻す
          RELEASE_TAG: v202402261910
        with:
          # 自動でpublishまでする場合コメントアウトを外す
          # publish: true
          name: Release v202402261910
          tag: v202402261910
          version: v202402261910